# Nacos Config 配置
spring:
  application:
    name: qihangerp-oms-api
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:qihangerp-scm.yaml?refresh=true
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: cn.qihangerp.oms.domain;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志

user:
  password:
    maxRetryCount: 5 #密码最大错误次数
    lockTime: 10 #密码锁定时间（默认10分钟）