# Nacos Config 配置
spring:
  application:
    name: store-api
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:qihangerp-scm.yaml?refresh=true


server:
  port: 8084
user:
  password:
    maxRetryCount: 5 #密码最大错误次数
    lockTime: 10 #密码锁定时间（默认10分钟）
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: cn.qihangerp.api.domain;com.qihangerp.api.common.security;cn.qihangerp.model.goods.domain;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志